FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Directorios de trabajo para volúmenes montados
RUN mkdir -p data artifacts reportes mlruns

ENV MLFLOW_TRACKING_URI=file:///app/mlruns

CMD ["python", "main.py", "--sintetico"]
